[package]
name = "lumatrix"
version = "0.1.0"
description = "Lumatrix 3D scene editor"
authors = ["Lumatrix"]
edition = "2021"

[lib]
name = "lumatrix_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"

