import AssetPreview from '../editor/components/AssetPreview.jsx';
import { ROAD_TYPES } from '../presets/catalog.js';
import { BRIDGE_PRESETS } from '../presets/bridgePresets.js';

export default function RoadLibrary({ road, bridge, mode, shape, continuous, onShape, onContinuous, onRoad, onBridge, onFinish }) {
  return <div><div className="road-shape-controls"><div className="road-library-kind" role="group" aria-label="도로 또는 교량"><button aria-pressed={!bridge} onClick={() => onRoad(road)}>도로</button><button aria-pressed={!!bridge} onClick={() => onBridge(bridge || 'small')}>교량</button></div>{!bridge && <label>형태<select aria-label="도로 형태" value={shape} onChange={e => onShape(e.target.value)}><option value="straight">직선</option><option value="curve">곡선</option><option value="roundabout">원형 도로</option></select></label>}<label><input type="checkbox" checked={continuous} onChange={e => onContinuous(e.target.checked)} />연속 배치</label><button onClick={onFinish}>배치 종료</button></div>
    <p className="road-placement-hint">{bridge ? '육지 시작점 → 반대편 육지 끝점 클릭 · 기존 도로 끝·중심선에 자동 연결' : shape === 'curve' ? '시작점 → 끝점 → 곡률 조절 후 클릭' : shape === 'roundabout' ? '중심 클릭 → 반경 조절 후 클릭 · 반경 8~40 m' : '시작점 → 끝점 클릭 · 기존 도로에 자동 연결'} · Esc로 종료 · 부지는 직접 조성합니다.</p>
    <div className="asset-list">{bridge ? BRIDGE_PRESETS.map(preset => <button key={preset.id} className={`asset-card bridge-card ${mode === 'road' && bridge === preset.id ? 'selected' : ''}`} onClick={() => onBridge(preset.id)}><AssetPreview asset={preset} kind="bridge" /><b>{preset.name}</b><small>{preset.detail}</small><span className="asset-size">{preset.type === 'path' ? '보행 전용' : preset.type === 'avenue' ? '왕복 4차로' : '왕복 2차로'} · 길이 {preset.min}~{preset.max} m</span></button>) : ROAD_TYPES.map(type => <button key={type.id} className={`asset-card road-card ${mode === 'road' && road === type.id ? 'selected' : ''}`} onClick={() => onRoad(type.id)}><AssetPreview asset={type} kind="road" /><b>{type.name}</b><small>{type.detail}</small><span className="asset-size">폭 {type.width} m</span></button>)}</div>
  </div>;
}
